.\" Manpage for kompex sqlite wrapper
.TH man 3 "14 April 2012" "1.0" "Kompex SQLite Wrapper man page"
.SH NAME
Kompex SQLite Wrapper \- an open source C++ wrapper library for SQLite.
.SH DESCRIPTION
The Kompex SQLite Wrapper is an open source C++ wrapper library for SQLite. 

The Wrapper wraps the SQLite C-functions and can be used on Windows and Linux operating systems.

It supports a wide range of SQLite functions and is up to date.

.SS Why should I use this wrapper?!
it is easy to use (see examples)
.br
integral exception handling
.br
transaction support
.br
wide range of SQLite functions supported
.br
std::count and std::cerr stream redirection
.br
well documented
.br
standard C++ source code (Linux and Windows portable)
.br
wrapper can be used as shared or static library
.br
database usage in memory
.br
UTF-8 and UTF-16 support

.SH SEE ALSO
Online documentation:
http://sqlitewrapper.kompex-online.com/index.php?content=documentation

.SH AUTHOR
Kompex SQLite Wrapper: 
Sven Broeske (SvenBroeske@web.de)

GNU-style port:
Geoffroy Planquart (geoffroy@aethelflaed.com)
